"use client";

import { useState } from "react";
import { Database, Link2, GitCommit, ShieldCheck, HelpCircle, ArrowRight } from "lucide-react";

interface Field {
  name: string;
  type: string;
  required: boolean;
  unique?: boolean;
  validation?: string;
  refersTo?: string;
  description: string;
}

interface CollectionSchema {
  name: string;
  description: string;
  fields: Field[];
  relations: {
    type: "outgoing" | "incoming";
    localField: string;
    foreignCollection: string;
    foreignField: string;
    description: string;
  }[];
}

const SCHEMA_DATA: Record<string, CollectionSchema> = {
  patients: {
    name: "Patients",
    description: "Stores demographic details, contact information, and medical histories of registered patients.",
    fields: [
      { name: "_id", type: "ObjectId", required: true, unique: true, description: "Primary Key automatically generated by MongoDB." },
      { name: "patient_name", type: "String", required: true, validation: "Trimmed", description: "The full legal name of the patient." },
      { name: "dob", type: "Date", required: true, description: "Date of birth, used for age calculation." },
      { name: "gender", type: "String", required: true, validation: "Enum (Male, Female, Other)", description: "The biological gender of the patient." },
      { name: "blood_group", type: "String", required: true, validation: "Enum (A+, A-, B+, B-, O+, O-, AB+, AB-)", description: "Blood group category." },
      { name: "contact", type: "String", required: true, unique: true, validation: "Regex: ^\\d{1,10}$", description: "Mobile/landline number. Must be numeric and max 10 digits." },
      { name: "email", type: "String", required: true, unique: true, validation: "Regex match, Lowercase", description: "Email address. Must be unique and formatted correctly." },
      { name: "address", type: "String", required: false, description: "Optional street/city mailing address." },
      { name: "medical_history", type: "String", required: false, description: "Chronic illness records, allergies, or surgical history." },
      { name: "createdAt", type: "Date", required: true, description: "Timestamp of registration (auto-generated)." },
      { name: "updatedAt", type: "Date", required: true, description: "Timestamp of last modification (auto-generated)." }
    ],
    relations: [
      { type: "incoming", localField: "_id", foreignCollection: "Admissions", foreignField: "patient_id", description: "A patient's file is referenced to track their hospital admissions." }
    ]
  },
  doctors: {
    name: "Doctors",
    description: "Contains directories of clinical physicians, details on specializations, and staff compensation.",
    fields: [
      { name: "_id", type: "ObjectId", required: true, unique: true, description: "Primary Key automatically generated by MongoDB." },
      { name: "doctor_name", type: "String", required: true, validation: "Trimmed", description: "Full name of the physician prefixed with Dr." },
      { name: "specialization", type: "String", required: true, validation: "Trimmed", description: "Clinical specialization area (e.g., Cardiology, Neurology)." },
      { name: "contact", type: "String", required: false, validation: "Regex: ^\\d{1,10}$", description: "Staff cell phone number. Must be numeric and max 10 digits." },
      { name: "salary", type: "Number", required: false, validation: "Min: 0", description: "Annual base salary compensation." },
      { name: "createdAt", type: "Date", required: true, description: "Timestamp of profile creation." },
      { name: "updatedAt", type: "Date", required: true, description: "Timestamp of last profile edit." }
    ],
    relations: [
      { type: "incoming", localField: "_id", foreignCollection: "Admissions", foreignField: "doctor_id", description: "A doctor is linked to admissions to represent they are the attending physician." }
    ]
  },
  wards: {
    name: "Wards",
    description: "Represents physical hospital departments and ward units (e.g. ICU, General, Pediatrics) with strict capacity bounds.",
    fields: [
      { name: "_id", type: "ObjectId", required: true, unique: true, description: "Primary Key automatically generated by MongoDB." },
      { name: "ward_name", type: "String", required: true, validation: "Trimmed", description: "The department name of the ward." },
      { name: "ward_number", type: "String", required: true, unique: true, validation: "Trimmed", description: "Unique code identifier (e.g., ICU-101)." },
      { name: "capacity", type: "Number", required: true, validation: "Min: 1", description: "Max count of physical beds allowed in the ward." },
      { name: "createdAt", type: "Date", required: true, description: "Timestamp of ward unit addition." },
      { name: "updatedAt", type: "Date", required: true, description: "Timestamp of last ward configuration change." }
    ],
    relations: [
      { type: "incoming", localField: "_id", foreignCollection: "Beds", foreignField: "ward_id", description: "A ward holds multiple physical bed units." },
      { type: "incoming", localField: "_id", foreignCollection: "Admissions", foreignField: "ward_id", description: "An admission records which ward department the patient is residing in." }
    ]
  },
  beds: {
    name: "Beds",
    description: "Physical bed units placed inside a clinical ward unit, managed for status occupancy.",
    fields: [
      { name: "_id", type: "ObjectId", required: true, unique: true, description: "Primary Key automatically generated by MongoDB." },
      { name: "bed_number", type: "String", required: true, validation: "Compound Unique Index with ward_id", description: "Bed number or code identifier (must be unique within the same ward)." },
      { name: "ward_id", type: "ObjectId", required: true, refersTo: "Wards", description: "Reference indicating which Ward this bed is located inside." },
      { name: "type", type: "String", required: true, validation: "Enum (General, ICU, Paediatric)", description: "Type classification of bed equipment." },
      { name: "status_available", type: "Boolean", required: true, validation: "Default: true", description: "Occupancy state indicator. Toggled when patient gets admitted or discharged." },
      { name: "createdAt", type: "Date", required: true, description: "Timestamp of bed addition." },
      { name: "updatedAt", type: "Date", required: true, description: "Timestamp of last bed status updates." }
    ],
    relations: [
      { type: "outgoing", localField: "ward_id", foreignCollection: "Wards", foreignField: "_id", description: "Links to the physical department ward where the bed belongs." },
      { type: "incoming", localField: "_id", foreignCollection: "Admissions", foreignField: "bed_id", description: "Beds are assigned to admissions to track active patient accommodations." }
    ]
  },
  admissions: {
    name: "Admissions",
    description: "The primary linkage entity recording patient hospitalization details, attending physicians, and bed assignments.",
    fields: [
      { name: "_id", type: "ObjectId", required: true, unique: true, description: "Primary Key automatically generated by MongoDB." },
      { name: "patient_id", type: "ObjectId", required: true, refersTo: "Patients", description: "Reference linking to the admitted patient record." },
      { name: "doctor_id", type: "ObjectId", required: true, refersTo: "Doctors", description: "Reference linking to the attending doctor roster." },
      { name: "bed_id", type: "ObjectId", required: true, refersTo: "Beds", description: "Reference linking to the specific bed assigned to the patient." },
      { name: "ward_id", type: "ObjectId", required: true, refersTo: "Wards", description: "Reference linking to the target department ward." },
      { name: "admission_date", type: "Date", required: true, validation: "Max Today", description: "Date of admission. Cannot be set in the future." },
      { name: "discharge_date", type: "Date", required: false, description: "Date of discharge. Populated when patient leaves." },
      { name: "status", type: "String", required: true, validation: "Enum (Admitted, Discharged, Critical)", description: "Current hospitalization condition status." },
      { name: "createdAt", type: "Date", required: true, description: "Timestamp of admission logging." },
      { name: "updatedAt", type: "Date", required: true, description: "Timestamp of last modification." }
    ],
    relations: [
      { type: "outgoing", localField: "patient_id", foreignCollection: "Patients", foreignField: "_id", description: "Interlinks the admission to the patient." },
      { type: "outgoing", localField: "doctor_id", foreignCollection: "Doctors", foreignField: "_id", description: "Attaches the clinical physician to the admission." },
      { type: "outgoing", localField: "bed_id", foreignCollection: "Beds", foreignField: "_id", description: "Allocates the physical bed to the patient." },
      { type: "outgoing", localField: "ward_id", foreignCollection: "Wards", foreignField: "_id", description: "Assigns the department ward location." },
      { type: "incoming", localField: "_id", foreignCollection: "Billing", foreignField: "admission_id", description: "An admission records invoices generated for the duration of stay." }
    ]
  },
  billing: {
    name: "Billing",
    description: "Hospital billing and collection accounts, logging balances associated with a patient's hospitalization duration.",
    fields: [
      { name: "_id", type: "ObjectId", required: true, unique: true, description: "Primary Key automatically generated by MongoDB." },
      { name: "admission_id", type: "ObjectId", required: true, refersTo: "Admissions", description: "Reference linking this bill statement to the specific admission record." },
      { name: "total_amount", type: "Number", required: true, validation: "Min: 0", description: "Total billing amount in USD. Must be a positive decimal." },
      { name: "payment_status", type: "String", required: true, validation: "Enum (Pending, Paid, Partial)", description: "Payment classification status." },
      { name: "bill_date", type: "Date", required: true, description: "Date of invoice issue." },
      { name: "createdAt", type: "Date", required: true, description: "Timestamp of billing creation." },
      { name: "updatedAt", type: "Date", required: true, description: "Timestamp of last billing edits." }
    ],
    relations: [
      { type: "outgoing", localField: "admission_id", foreignCollection: "Admissions", foreignField: "_id", description: "Links invoice to the stay and patient registry details." }
    ]
  }
};

export default function SchemaRelationsPage() {
  const [selectedKey, setSelectedKey] = useState<string>("admissions");
  const [hoveredKey, setHoveredKey] = useState<string | null>(null);

  const activeKey = hoveredKey || selectedKey;
  const currentCollection = SCHEMA_DATA[activeKey];

  // Helper to check if a collection card is connected to the currently active card
  const getRelationStatus = (key: string) => {
    if (activeKey === key) return "active";

    const activeSchema = SCHEMA_DATA[activeKey];
    const hasConnection = activeSchema.relations.some(
      (rel) => rel.foreignCollection.toLowerCase() === key
    );

    return hasConnection ? "connected" : "dimmed";
  };

  return (
    <div className="space-y-6">
      {/* Header section */}
      <div>
        <h2 className="text-2xl font-bold text-white tracking-wide flex items-center gap-2.5">
          <Database className="h-6 w-6 text-green-400" />
          Database Schema & Relations
        </h2>
        <p className="text-sm text-gray-400">
          Interactive map of MongoDB collections, Mongoose schema validation constraints, and relational foreign keys.
        </p>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">
        {/* Left Side: Interactive Grid Map */}
        <div className="xl:col-span-2 space-y-6">
          <div className="dashboard-card p-6">
            <h3 className="text-sm font-bold text-white tracking-wider mb-4 uppercase text-gray-400">
              Interactive Schema Map
            </h3>
            <p className="text-xs text-gray-500 mb-6 leading-relaxed">
              Hover over or click a card to highlight its primary linkages (foreign key relationships) with other collections. Green borders indicate the source; blue borders represent direct connections.
            </p>

            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-5">
              {Object.entries(SCHEMA_DATA).map(([key, schema]) => {
                const status = getRelationStatus(key);

                let cardBorderClass = "border-gray-800 bg-[#0d0d15]/60 opacity-60";
                let badgeClass = "bg-gray-800 text-gray-400";
                if (status === "active") {
                  cardBorderClass = "border-green-400 bg-green-500/5 shadow-lg shadow-green-500/5 opacity-100 scale-[1.02] ring-1 ring-green-400/20";
                  badgeClass = "bg-green-400/20 text-green-400";
                } else if (status === "connected") {
                  cardBorderClass = "border-blue-400 bg-blue-500/5 shadow-lg shadow-blue-500/5 opacity-100 scale-[1.01] ring-1 ring-blue-400/20";
                  badgeClass = "bg-blue-400/20 text-blue-400 animate-pulse";
                }

                return (
                  <button
                    key={key}
                    onClick={() => setSelectedKey(key)}
                    onMouseEnter={() => setHoveredKey(key)}
                    onMouseLeave={() => setHoveredKey(null)}
                    className={`p-5 rounded-xl border text-left flex flex-col justify-between h-36 transition-all duration-200 cursor-pointer ${cardBorderClass}`}
                  >
                    <div>
                      <div className="flex justify-between items-start">
                        <h4 className="text-sm font-bold text-white tracking-wide">{schema.name}</h4>
                        <span className={`px-2 py-0.5 text-[9px] font-bold uppercase rounded ${badgeClass}`}>
                          {status === "active" ? "Focus" : status === "connected" ? "Linked" : "Table"}
                        </span>
                      </div>
                      <p className="text-[11px] text-gray-400 mt-2 line-clamp-2 leading-relaxed">
                        {schema.description}
                      </p>
                    </div>
                    <div className="flex items-center gap-1.5 text-[10px] font-semibold text-gray-500 mt-3 hover:text-white transition-colors">
                      View fields ({schema.fields.length})
                      <ArrowRight className="h-3 w-3" />
                    </div>
                  </button>
                );
              })}
            </div>

            {/* Visual Relationships List */}
            <div className="mt-8 pt-6 border-t border-gray-800/60">
              <h4 className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-4">
                Relations of: <span className="text-green-400 font-bold">{SCHEMA_DATA[activeKey].name}</span>
              </h4>
              <div className="space-y-2.5">
                {SCHEMA_DATA[activeKey].relations.map((rel, index) => (
                  <div
                    key={index}
                    className="flex flex-col sm:flex-row sm:items-center gap-3 p-3 rounded-lg bg-gray-900/40 border border-gray-800/80 text-xs"
                  >
                    <div className="flex items-center gap-2 text-white font-mono shrink-0">
                      <span className="text-green-400">{SCHEMA_DATA[activeKey].name}</span>
                      <span className="text-gray-600">.{rel.localField}</span>
                      {rel.type === "outgoing" ? (
                        <ArrowRight className="h-3.5 w-3.5 text-blue-400 mx-1 shrink-0" />
                      ) : (
                        <ArrowRight className="h-3.5 w-3.5 text-purple-400 mx-1 shrink-0 rotate-180" />
                      )}
                      <span className="text-blue-400">{rel.foreignCollection}</span>
                      <span className="text-gray-600">.{rel.foreignField}</span>
                    </div>
                    <div className="text-gray-400 flex items-center gap-1.5 leading-relaxed">
                      <Link2 className="h-3 w-3 text-gray-600 shrink-0" />
                      {rel.description}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Right Side: Detailed Schema Field Viewer */}
        <div className="xl:col-span-1 space-y-6">
          <div className="dashboard-card p-6 flex flex-col justify-between min-h-[500px]">
            <div>
              <div className="flex items-center gap-2 mb-2">
                <Database className="h-5 w-5 text-green-400" />
                <h3 className="text-base font-bold text-white tracking-wide">
                  {currentCollection.name} Schema
                </h3>
              </div>
              <p className="text-xs text-gray-400 leading-relaxed mb-5">
                {currentCollection.description}
              </p>

              <div className="space-y-3.5 max-h-[550px] overflow-y-auto pr-1">
                {currentCollection.fields.map((field) => (
                  <div
                    key={field.name}
                    className="p-3 rounded-lg bg-gray-900/40 border border-gray-800 hover:border-gray-700/80 transition-colors"
                  >
                    <div className="flex justify-between items-start gap-2">
                      <span className="text-xs font-mono font-bold text-white flex items-center gap-1">
                        {field.name}
                        {field.required && <span className="text-red-400" title="Required field">*</span>}
                      </span>
                      <div className="flex items-center gap-1.5 shrink-0">
                        {field.refersTo && (
                          <span className="px-1.5 py-0.5 text-[9px] font-bold bg-blue-500/10 text-blue-400 border border-blue-500/10 rounded flex items-center gap-0.5">
                            <Link2 className="h-2 w-2" />
                            Ref: {field.refersTo}
                          </span>
                        )}
                        <span className="px-1.5 py-0.5 text-[9px] font-mono rounded bg-gray-800 text-gray-400 font-semibold border border-gray-700">
                          {field.type}
                        </span>
                      </div>
                    </div>
                    <p className="text-[10px] text-gray-400 mt-1.5 leading-relaxed">
                      {field.description}
                    </p>
                    {(field.validation || field.unique) && (
                      <div className="flex flex-wrap gap-1.5 mt-2">
                        {field.unique && (
                          <span className="px-1.5 py-0.2 text-[8px] font-bold bg-yellow-500/10 text-yellow-400 border border-yellow-500/10 rounded uppercase">
                            Unique
                          </span>
                        )}
                        {field.validation && (
                          <span className="px-1.5 py-0.2 text-[8px] font-bold bg-green-500/10 text-green-400 border border-green-500/10 rounded">
                            {field.validation}
                          </span>
                        )}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>

            <div className="mt-6 pt-5 border-t border-gray-800/60 flex items-center gap-2 text-[10px] text-gray-500 font-semibold">
              <ShieldCheck className="h-4 w-4 text-green-400" />
              Mongoose Schema Validation Active
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
